# Generated by Django 5.2.7 on 2025-11-10 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
